### ISSUE TITLE
Placeable Cardtable Excessively large footprint

### ISSUE THREAD

**Issue by Anatida** [Beamdog/nwn-issues#109]
**Description**

In testing the Cardtable  placeable from the Tyrants Art Pack, the table has an excessively large footprint and use glow when set to 'useable'.

**To Reproduce**

 - Place the placeable Cardtable.
 - Set the cardtable to be 'useable'.
 - Enter the game as player and move around the cardtable.

**Specifics**

 - Game build 8193.13
 - OS Windows 10
 - Distro platform Steam
 - This is tested by using the Tyrants' Artpack contents in a hak on Arelith PW server.

![image](https://user-images.githubusercontent.com/50813811/86948917-7d5ce200-c113-11ea-953d-ea61f039ac67.png)
![image](https://user-images.githubusercontent.com/50813811/86948955-8c439480-c113-11ea-88f5-ef9433c46561.png)

**Comment by Bill-Harper** [comment]
![card_table_hit-box](https://user-images.githubusercontent.com/53191846/87323612-018cdc00-c4fd-11ea-8495-7ad70c6a4ccb.png)

This one cleaned up fairly easily, must have been a bad export because the pivots were in place. Fortunately narrow enough to allow usage, because it seems to have the same problem as the dice table (ignoring the Use dummies, aiming for dead center).
