### ISSUE TITLE
Game starting in windowed mode on Linux

### ISSUE THREAD

**Issue by jd28** [Beamdog/nwn-issues#118]
**To Reproduce**

 - Run the game from steam.

**Specifics**

 - OS (Windows, Mac, Linux) - Linux
 - Game build (e.g. 8193.8, or commit hash) - 8193.13
 - Distro platform (BDC, Steam, GOG) - Steam
 - Content overrides? (Steam Workshop? Overrides? Patch haks?) - None, fress install.

**If needed, describe the bug**

I might be misinterpreting previous change logs, but I thought only MacOS was defaulted to window mode.  Attached is a screenshot running the game from default steam install on Manjaro Linux 20.0.3. 

![Screenshot_20200713_031052](https://user-images.githubusercontent.com/540002/87294019-ff545e80-c4b7-11ea-9714-d15f570b02fc.png)

**Comment by DMSymphony** [comment]
JD,

The defaults are part of the generation of the settings.tml file. When the file is created (game ran without a settings.tml pre-existing), it uses the default values. All operating systems use settings.tml, and the settings.tml defaults are at the bottom of the file in the ~~schema section.

While there's probably a bit of a war between defaulting to full screen with players never knowing you COULD play in windowed, and defaulting to windowed with players never knowing you COULD play in full screen, I think it's probably safest/smartest to start the game in windowed mode, which will use your desktop resolution.

If the game defaulted in exclusive full screen, as 1.69 did, this can force a resolution change, and a refresh rate change, and in the event that those defaults are out of range for the display (too high or too low), it can be very troublesome for first time installers to resolve. Whereas, in situations like your screenshot above, resizing with corner dragging, or using/googling/asking about the OS full screen command (Alt + Enter) is a lot more forgiving.

Meanwhile, future patches will have likely have full screen / window modes in the options, once the Bioware options are replaced by new Beamdog menus with the new available settings.

I think the biggest casualty here so far is players that do not realize that maximized and full screen are not the same thing, who cannot use screen edge turning mode because of it.

**Comment by jd28** [comment]
That makes sense.  I appreciate you taking the time to explain.  I must have a settings.tml generated from a previous version of nwserver-linux.
