### ISSUE TITLE
Spells.2da spelling errors and incorrect values

### ISSUE THREAD

**Issue by enigmaticaljedi** [Beamdog/nwn-issues#127]
**To Reproduce**

 - Extract and view the Spells.2da file
 - Follow the table below in specifics to see the errors and incorrect values

**Specifics**

| ID | Spell | Column | Current Value | Correct Value | Reason |
|--|--|--|--|--|--|
|12|Calm_Emotions|ImmunityType|Mind_Effecting|Mind_Affecting|Incorrectly spelling, should be "A" not "E"|
|*|*|ImmunityType|Mind-Affecting|Mind_Affecting|There are 34 spells with underscore (_) and 23 spells with a dash (-)|
|114|Mass_Heal|ImmunityType|Postive|Positive|Missing the "i" after the "s" in the spelling of Positive|
|124|Natures_Balance|ImmunityType|Postive|Positive|Missing the "i" after the "s" in the spelling of Positive|
|801|Azer_Fire_Blast|ImmunityType|1|Fire|Incorrect value of "1" is in this column instead of "Fire"|

**Effects of the above errors**

The toolset uses these values in scripts and in character creation to assist with the selections of spells. Having these incorrect values may cause those spells not to work correctly or be selected properly.

Effects of this bug would include:
- Not correctly applying immunity to those spells or monster effects

**Comment by Finaldeath** [comment]
Sadly while the spells.2da has some legitimate issues (such as "Master" column being wrong in some cases I need to document fully) these columns do absolutely nothing in the game and do nothing at all AFAIK. They don't assist in anything to do with character creation either, which relies instead on (sometimes in correct) dialog.tlk file entry and packages.2da entries.

Trust me, blanking it out or seeing that many spells have 2 saves or many different effects (eg; Prismatic Spray) and then you look at the spell script and that is where it actually specifies any immunities, by hand (whether or not the script is correct is another topic entirely).

I'm not sure where people get this idea. Perhaps because nwn.fandom.com is wrong a lot of the time in regards to 2da column values and this one is no exception.

**Comment by enigmaticaljedi** [comment]
@Finaldeath can you tell me if this is the same for the other .2da files?

I have found a wide variety of errors across multiple 2da files including:

- class_feat tables that have repeated ID numbers
- tables that include quoted text (wingmodel, placeables)
  - (The only one I thought this was allowed was ruleset.2da)
- files using tabs instead of spaces (des_xp_rewards, categories)


Is there any point in reporting any of these to be fixed?

**Comment by Finaldeath** [comment]
Okay so I'd probably report egregious issues - I've found a few actual issues in spells.2da (eg; targeting choices etc.).

2das are pretty...well, weird? Those things are not actually issues (I need to write up a nwn.wiki page on 2da files!):
* Repeated ID numbers - the ID field is just for human readability, it isn't used by the game at all in fact (although it'd be nice to have them all line up properly, what ones are these?). If you wondered the game actually just reads each new line in as a new entry
* Tabs are whitespace and are not an issue, it only needs one whitespace character to separate fields. Of course for editing purposes having a mix is a PITA.
* Quoted fields are supported in 2das since just after the games release (just Bioware rarely used them), sometimes they can be properly loaded in, instead of TLK numbers, but not always. If used as part of a "Label" field this column isn't even loaded by the game AFAIK, so as long as the quotes are properly around the entire field entry the game ignores it anyway.

What is more pressing I'd say (not Beamdog myself, but from a perspective of correct data and bugs):

* 2da fields which are just 100% wrong (some spells.2da things like targeting, invalid Master column), which cause bugs in general use cases
* 2da fields which crash the game when accessed/used
* 2da fields which upset the game systems (eg level up packages being dodgy)
* 2da fields which are being added for new base game content which have obvious issues (Ossian additions for instance if they were copied in wrongly with odd values)
* 2da fields that are improperly formatted (text in a number field) which only doesn't cause an issue because that particular line isn't used much or at all, but if used suddenly causes odd issues

If you want we can have a look at what you've found on nwvault discord? I'm always interested in bugs around basic stuff like this just because I'm doing several bits of  2da reads in my AI and it's been a bit...hamstrung...by the 2das being wrong! :)

**Comment by enigmaticaljedi** [comment]
Thanks for the info...

I have started to find other issues which make it difficult to "parse" the values consistently:

* **des_crft_spells.2da** - Line 702 is just empty
* **effectanim.2da** - duplicated the ID field (Wouldn't this mean the radius is **incorrectly** 1 not 2.0?)
* **keymap.2da** - contains **non-quoted** text in the last row
* **packeqdruid1.2da** - has additional values just hanging in the middle of nowhere for the first 2 rows

Regarding the "label column"... In order to actually identify that the data is in fact part of "the label column", you have to parse the values. I understand that quotes were supported _in some places_ early on, but to suddenly start introducing it into new files that haven't used them before is frustrating, let alone the fact that in keymap.2da they just decided to leave the quotes out altogether (which I guess also gets ignored because its the last row and I am guessing this is just a misnamed "Label" column at the end called "Name"?)

Regarding duplicate numbering though, if it isn't used but just human readable, you are assuming that whenever those fields are referenced elsewhere that they "know" there are duplicates and have purposely added +1 to their reference so that they are correctly pointing to the right row. How would we even know if this is causing a problem given it is likely to be insidiously off by one (ie instead of pointing to` weapon focus (longsword)` it is pointing to `weapon focus (greatsword)`)

As it stands at the moment, I have to have a "fixes" file to correct the mistakes on the fly

**Comment by Finaldeath** [comment]
Basically since 2das are so simple the game probably  "doesn't worry" about some of that, I very much doubt it does regex:

* des_crft_spells.2da - Used by spell crafting so just Get2DAString accesses it so an empty line won't do much (and it's the last one anyway)
* effectanim.2da isn't used by the game AFAIK (there's a few others that are simply unused you can ignore)
* keymap.2da error looks like it has unquoted text (worth fixing, several lines has it), but no header for columns it probably just stops reading
* packeqdruid1.2da is probably ignored (since there is no header column defined)

If the field has quotes around it it'll ignore spaces until it gets to another quote symbol (obviously those fields loaded in as integers or whatever won't have this occur). Regex to understand this is probably...not the best idea. A loop of the characters on a line and you can read 2da data "properly", which is very likely how the game does it. :)

The duplicate numbering can and has broken "reference numbers" before, you can read very old Bioware patch notes that reference that. Alas the examples you've pointed out though are not referenced by anything so it'd just be read by the game. As I said before they're worth fixing IMO but you'd need to provide a full list so maybe post all the errors and Beamdog may take a look at fixing them.

Apart from a few entries in spells.2da and feats.2da just being bad data (eg; Bless being a medium range spell, but the spell script is cast on self so should be personal only, or some spells having a Master spell set even if they're not a subspell of them) I've not seen anything much that has broken the game, as in caused a condition that means something doesn't work as intended.

**Comment by Finaldeath** [comment]
Data issue not planned to fix.
