### ISSUE TITLE
[8193.16] Random Toolset Crashes When Changing Areas

### ISSUE THREAD

**Issue by ghost** [Beamdog/nwn-issues#163]
**To Reproduce**

 - Open the enclosed module in the Toolset.
 - Makes sure that the "Open Areas in Tabs" option is off.
 - Open any area other than "Greenhaven".
 - Edit or create a template for a creature, item, or placeable OR open and edit a script.
 - Open the "Greenhaven" area.
 - Toolset crashes.

**Specifics**

 - Game build 8193.16
 - Regression? Didn't happen in 8193.14, started in 8193.15.

**If needed, describe the bug**

The crash is random at best and not easy to repro. It seems to occur at random intervals and not always due to the same cause. The module, afaik, isn't corrupted and you can play the module in game with no issues. I'm not sure if this is caused by custom content in the Greenhaven area or by something in the Toolset. The crashing seems to occur more often with 8193.16 than it did with 8193.15.

I have attached a link to the module and haks for CC used in it.

https://www.dropbox.com/s/8d6v361lhfh4tl7/Crash.zip?dl=0

**Comment by Balanor** [comment]
To add to this-
Since updating to .16, the toolset has been very unreliable for me when opening multiple areas, and will often crash with the following error that cannot be closed (clicking OK only produces another identical error). The toolset can only be closed by killing it via the Task Manager when this happens.
![image](https://user-images.githubusercontent.com/36014329/96175607-bcf45080-0ef0-11eb-9457-d3ea300accfc.png)

**Comment by pstemarie** [comment]
Balanor, have you tried updating to the the latest DEV or PREVIEW patch. The toolset is far more stable for me than it was in STABLE .16. I haven't experienced a crash since the latest PREVIEW came out.
