### ISSUE TITLE
[8193.16] Forest - Facelift tile ttf02_t13_01 is incomplete

### ISSUE THREAD

**Issue by Balanor** [Beamdog/nwn-issues#186]
**Description**
Tile ttf02_t13_01 is missing the tent door flap along with a portion of the tent by the door, which allows you to see through it to the grass underneath. In addition, the wooden stakes for the small lean-to next to the tent, the chopped wood under the lean-to, 2 of the 3 wooden stakes for the firepit, some wood under the fire, and all but one of the rocks surrounding the firepit are all missing. 
See the attached screenshots for comparison of the ttf02_t13_01 tile vs ttf01_t13_01 from the original Forest tileset.
![ttf02_t13_01 issues](https://user-images.githubusercontent.com/36014329/95104246-37f08680-06fb-11eb-93ee-232cdd02f276.jpg)

**To Reproduce**
1. Create a new area using the Forest - Facelift tileset
2. Place the Camp 1 2x2 tileset group
3. Find tile ttf02_t13_01 in this group (just to the left of the door, which encompasses the firepit) and note the missing components on that tile.

**Specifics**
 - 8193.16
 - Windows
 - BDC and Steam
 - Content overrides? No
 - Regression? No

**Comment by Bill-Harper** [comment]
Thanks for the report! Turns out several meshes, including some rocks and logs, had Render set to 0 somehow (export bug)? I got these back to 1, fixed some UV's on the once-missing tent flap, and added bottom mesh to the lean-to cover over the firewood (thus fixing ttf02_t14_01 as well).

![ttf02_t13-14_01](https://user-images.githubusercontent.com/53191846/95330125-149e1680-0876-11eb-8dad-48608b710f8f.png)
