### ISSUE TITLE
[81.8193.18] Dual screen are automatically set to mirroring, but screens stay black

### ISSUE THREAD

**Issue by julien-lecomte** [Beamdog/nwn-issues#211]
**To Reproduce**

 - Problem exists with at least .18 version
 - Have two screens: 27" + 24". 27 is primary, 24 is secondary, to the right of 27, and in rotated mode.
 - Start nwn

**Specifics**

 - Debian Buster, GeForce GTX 970, nouveau drivers
 - After .18
 - Steam
 - Regression? YES. Works fine in .17

**If needed, describe the bug**

A clear and concise description of what the bug is if the repro steps do not make it obvious. *No essays!* Assume whoever reads this has not had coffee.

If warranted, add videos/screenshots to showcase the issue.

**Comment by julien-lecomte** [comment]
Of note, to get the hand back on the computer, I have to ctrl-alt-F1, log in, and kill my whole xfce session with `kill -9 -1`.

**Comment by julien-lecomte** [comment]
![20201111_134516_resized](https://user-images.githubusercontent.com/1992050/98816018-564b4f80-2428-11eb-870c-f2c55b7f9022.jpg)

**Comment by julien-lecomte** [comment]
On .17, the screen to the right is not used by NWN, and that was fine for me.

**Comment by Soren217** [comment]
Odd. Could you try to revert to .17 and verify that it works again?

**Comment by julien-lecomte** [comment]
Worked without issue on .17. 
Talked with niv about this on discord. 

Setting were:
```
  [graphics.window]
    mode = "exclusive"
    [graphics.window.fullscreen]
      height = 1080
      toggle-to-borderless = false
      width = 1920
    [graphics.window.windowed]
      borderless = false
      height = 1033
      width = 1910
      [graphics.window.windowed.position]
        mode = "remember" 
        x = 5
        y = 42
```

With the settings above both screens become black. In the meanwhile, it also changes the settings file to  graphics.window.fullscreen.height to 1920 and width to 3000.

**Comment by DMSymphony** [comment]
I have three monitors, and was able to use .18 and .19 without issue with full screen and windowed modes, in Ubuntu 20.04.

It sounds to me like you have some sort of composite "stretched" display, where the displays are summed rather than separated. The 3000 width is 1920+1080, which is the total width of your display configuration, if honoring your monitor orientation.

I am not sure how you could have this issue now and not have had it during your entire NWN on Linux experience, but, your preferences to play the game in full screen with a separate monitor already suggest to me that you are a good candidate for borderless windowed mode.

Placing the window position at 0 0, and using the mode = "windowed" instead of "exclusive", with a 1920 x 1080 window.windowed and borderless = true, would give you a full screen experience on the left monitor, barring cursor trapping for screen edge turning, allowing you to use the portrait monitor for multitasking if desired.

**Comment by DMSymphony** [comment]
@julien-lecomte Sorry, I am wrong, since I was using a different version of .18 and .19 that I had prepared for other testing, that do not have issues.

There does seem to be some very weird display issues with the distributed versions of .18 and .19 in all Linux environments, when using full screen, and, I would suggest that you use borderless windowed mode, as suggest above, until they can be fixed.

**Comment by julien-lecomte** [comment]
Hi.
Thanks for the reply. I'm currently using the borderless windowed mode as a temporary workaround.

**Comment by julien-lecomte** [comment]
Confirm to be fixed in latest PREVIEW build.
