### ISSUE TITLE
[8193.21] - Plcs with texture5 illum map not working as intended (?)

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#220]
A model with an illumination map specified in texture5 of the mtr does not illuminate properly. Expected behavior is it illuminates blue same as the illum texture.  If texture5 in the mtr is set to null, the entire object seems to illuminate.

See below sshot in reset to black area: 
1 - this has illum texture specified in the mtr (mask illuminates, but faintly, no color)
2 - this has illum texture set to null in the mtr (entire object illuminates)

Attached are are the files.

Specifics

8193.21
Windows
Steam preview
Content overrides? Yes, as attached.

![with illum map](https://user-images.githubusercontent.com/62627607/100556978-f0f2bd80-3273-11eb-936a-7c39d5049d74.JPG)
![witout illum map](https://user-images.githubusercontent.com/62627607/100556979-f3551780-3273-11eb-8133-848edb45cc0f.JPG)
[tombstone.zip](https://github.com/Beamdog/nwn-issues/files/5613135/tombstone.zip)

**Comment by Soren217** [comment]
The way that illumination textures work presently, they actually use the base texture for the tone and then use only the first channel of the illumination map to set the intensity. 

I can see many reasons to prefer them having separate hues though (especially when used with scripting), so perhaps this should be changed. This will however break backward compatibility, though perhaps it's fair to assume that these maps have seen very limited use so far, so that may be less of an issue.

I'll ask around.
