### ISSUE TITLE
Gold can be given to placeables and is destroyed in the process

### ISSUE THREAD

**Issue by DangerDolphin** [Beamdog/nwn-issues#251]
**To Reproduce**

 - Select the gold icon in your inventory, enter an amount 
 - Your cursor will change to allow you to select where to put the gold
 - Click on any useable placeable
 - The gold disappears

**Specifics**

 - OS Windows
 - Game build 8193.20.1
 - Distro platform Steam
 - Content overrides - Some Haks, but none related to this
 - Regression? Has likely existed for a long time

**If needed, describe the bug**

This is a frequent misclick problem when giving gold to other player characters.

**Comment by TomRotfl** [comment]
Actually, the gold disappears **ONLY** if the placeable doesn't have the `Has Inventory` flag. If the flag is enabled, gold gets into the placeable inventory, otherwise its lost. I have added a workaround to this `OnUnacquireItem` of my PW. Checking that if the receiver is a placeable, and there is no `Inventory Flag`, the gold is returned to the player.
