### ISSUE TITLE
[8193.9] TN_SDoor02 Has Broken Animations

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#26]
**Description**

The animations are present in the model, but the cloth geometry has no movement. Not sure if its supposed to roll up, slide away, or fold away. This is the tile specific door for the Ice Cellar feature in TNO01 (see issue #25).

**Specifics**

 - Game build 8193.9
 - Windows 10
 - Steam

**Comment by Bill-Harper** [comment]
[tn_sdoor_02.zip](https://github.com/Beamdog/nwn-issues/files/4540187/tn_sdoor_02.zip) This was a tricky one. It looks like NWMax shredded the animesh upon import, and I had totally missed it months ago when first working on this. Tricky part was replacing the wg_closed dummy with a wg_closed mesh, so that drive mode still works, and keeping the old animesh--without breaking the MDL. I think it's working properly now?
