### ISSUE TITLE
[dev build 78a4a24d] Lighting has lost intensity

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#289]
**To Reproduce**

 - Open module attached and use included hak (placeable light nodes)
 - Compare stable (currently 20.1 [7cb918c0] to dev .21 [78a4a24d]; light nodes have lost intensity; see attached pic

**Specifics**

 - Windows
 - dev build 78a4a24d
 - Distro platform (Steam development branch)
 - See above for repro; empty override/dev
 - Regression? Yes, this one.
 
FILES
[dclites.zip](https://github.com/Beamdog/nwn-issues/files/6177494/dclites.zip)
![Capture](https://user-images.githubusercontent.com/62627607/111906622-c3e73800-8a27-11eb-80db-9c293182fe8a.JPG)
[module007.zip](https://github.com/Beamdog/nwn-issues/files/6177495/module007.zip)

**Comment by Soren217** [comment]
Actually, this is due to an error in version .13 to .20 with lights in compiled models that was fixed in the dev patch. The ranges they appear with now should very much match those in the model files themselves (and the range in their naming), and how they looked prior to .13. Try to check the appearance in .20 with the models uncompiled and compare.

In other words, it's the brighter version that's wrong. 

(And yes, it's super unfortunate and I'm very sorry for that mess!)
