### ISSUE TITLE
Wierd water placeable texture opacity change and invisible gems

### ISSUE THREAD

**Issue by Swogu** [Beamdog/nwn-issues#298]
**Description**

Water placeable changed texture in dev patch, looks wierd
Gems are almost
![before_patch](https://user-images.githubusercontent.com/81535877/112769282-e0d3ca80-9028-11eb-8ce1-b0638589079a.PNG)
![after_patch_watergems](https://user-images.githubusercontent.com/81535877/112769284-e204f780-9028-11eb-9b05-eea4eb9016ab.PNG)
![gems_in_toolset](https://user-images.githubusercontent.com/81535877/112769286-e204f780-9028-11eb-85ee-b8e1cc864ea0.PNG)

 invisible

**To Reproduce**

 - Create any module
 - Set water placeable and gems placeable

**Specifics**

 - Game build 8193.21
 -  Windows
 - Steam

**Comment by Soren217** [comment]
The water opacity change is due to water now having opacity based on depth, which gives more natural looking water refraction, softer edges and well, generally more realism. In other words, your water is too shallow for it to be really seen other than as a wet layer right above the stone floor. You could try to elevate it a bit and see how that looks. At some point I figure making the water more customizable in terms of translucency could be a nice option, but meanwhile, you could also tweak the shader yourself to tailor it exactly to your liking.

Regarding the gems, could you perhaps provide a savegame or module that I could look at? Thanks :)
