### ISSUE TITLE
800x600 Resolution is no longer playable

### ISSUE THREAD

**Issue by WodahsEht** [Beamdog/nwn-issues#323]
Oversized UI elements such as the "Settings" menu as well as the "New Game" menu have made it impossible to play the game at 800x600 resolution as well as achieve a natural 2x scaling as was seen at 1080p on previous builds.  Rather than forcing resolutions up, it may be better to resize UI elements down to better fit.

**Comment by Finaldeath** [comment]
Wasn't there an explicit note that UI elements now were simply too large for 800x600 so you know this was intentional right?

I mean that's a super tiny resolution, and really limiting - you can't make text any smaller it just makes it unreadable and boxes of text just become as bad as the current server browser. The new singleplayer campaign selector (plus other potential larger UI elements like the options menu) is worth the sacrifice of a lower resolution if my two cents are worth anything.

**Comment by niv** [comment]
Yes, sorry. New minimum spec resolution is 1024x768 or equivalent.
