### ISSUE TITLE
[8193.23] - Linux - Systematic client crash on some specific custom heads and placeables

### ISSUE THREAD

**Issue by Chimerik** [Beamdog/nwn-issues#328]
The client always crash on some very specific custom heads and placeable.
We could only reproduce this on Linux systems. Windows clients are fine and never crash.

Please find attached one head model that always make linux clients crash.

[plantate_tete_48.zip](https://github.com/Beamdog/nwn-issues/files/6587574/plantate_tete_48.zip)

**Specifics**

 - Linux, Ubutun 20
 - 8193.23 (but it also happened on previous versions)
 - Steam
 - Repro Rate: 100%
 - Content overrides : the custom head attached

**Comment by Soren217** [comment]
Thanks for the report. I see that the material uses a custom shader - could you upload that as well?

**Comment by Soren217** [comment]
Also - have you tested whether it crashes on several Linux systems or is it just one?

**Comment by Chimerik** [comment]
Hi,

Here the requested custom shader:

[fslit_aniso_nm.zip](https://github.com/Beamdog/nwn-issues/files/6801903/fslit_aniso_nm.zip)

We don't have several Linux systems running, so we can't thorougly.

All I can say for sure is that our players with Ubuntu 20.4 LTS are crashing when this head is displayed in game whereas it displays fine for Windows users.

Thanks for help!

**Comment by LaputianBird** [comment]
From the sound of it, it might be that one of the node or material names are too long, around 31/32 characters - linux handles string terminators differently from windows, so that could explain why on an OS the name is too long and not on the other.
There's an open issue here on github that documents the client crash caused by long internal names

**Comment by LaputianBird** [comment]
https://github.com/Beamdog/nwn-issues/issues/53#issue-616748500

**Comment by LaputianBird** [comment]
I got curious and checked the model. One of the nodes is named `model001_7_hair_0_1_0_0_hand_ri0` which is 32 characters long, which is the theoretical max length of a string. However linux might be reading 33 characters (due to the string terminator difference) hence reading from illegal memory addresses.
Specific solution is to rename the node (including any internal references to it)

**Comment by LaputianBird** [comment]
The linux vs windows explanation might be inaccurate, it comes from what I remember of a conversation with clippy

**Comment by Chimerik** [comment]
A lower node name corrected the client crash issue, which means this issue is definitely related to #53 
I guess we can close this one. Thanks a lot for your help, birb!
