### ISSUE TITLE
Class Stat Tables not used during level up when determining feat eligibility or skill points

### ISSUE THREAD

**Issue by Jorteck** [Beamdog/nwn-issues#45]
**To Reproduce**
Non-Ability Level up:
 - Load the attached character, "pierofears1"
 - Level up and select RDD (becoming 9th level in the class)
 - Notice that the feat "Expertise" is unavailable despite meeting the feat requirements

Ability level up:
 - Load the attached character, "pierofears2"
 - Level up and select RDD (becoming 9th level in the class)
 - When prompted for ability selection, choose intelligence. The value will jump to the RDD bonus.
 - In the same GUI, reduce the ability back down and the bonus should stick. Then put this ability point anywhere
 - Notice that the feat "Expertise" is now available to select.

**Specifics**
- OS: Windows
- Build: 8193.9
- Distro: Steam
- Content overrides: None

**If needed, describe the bug**
When being granted an ability score bonus from a class stat table, the bonus is not considered until after the level up for the purposes of skill point increases and feat prerequisites, unless it is the same level that an ability increase is also selected.

In this case, if a player consumes the extra skill points, they will fail ELC with an error stating the character applied an invalid amount of skill points. If the player does not use this extra skill point however, they are able to take the feat unaffected.

[characters.zip](https://github.com/Beamdog/nwn-issues/files/4580344/characters.zip)

**Comment by eveferon** [comment]
Thanks for the report. It is a detailed one but might be a bit complex to find the issue.

One effect of the issue is simple and 100% reproducible on .14 build.

Take 2 level of RDD, it will give you +2 strengths. If you do **not** take strengths on this 2nd RDD level, y**ou will not get the regular +1 attack and +1 damage** from these +2 strengths. 

The bonus is given as soon as you increase the strength attribute on level up. If you don't, the character will remain lacking the bonuses.

Here is an example after level up 4 RDD on 1.69 and .14 EE bulld. The issue is Crystal clear and something players will definitely complain a lot about.

![image](https://user-images.githubusercontent.com/4124903/90987554-15137400-e58c-11ea-9dc4-dcb6f18cae4f.png)

I can provide the characters as well but since it is simply taking 2 lvl of RDD and not taking strengths on the 2nd level (and also because the chars are already provided), I am not sure it will add anything.

**Comment by eveferon** [comment]
[EE.bic.zip](https://github.com/Beamdog/nwn-issues/files/5117574/EE.bic.zip)
[169.bic.zip](https://github.com/Beamdog/nwn-issues/files/5117575/169.bic.zip)

Added two .bic files for simple comparison. Both characters are identic in respect of the issue. 1.69 version has the attack and damage bonuses from RDD attributes, the EE version does not. Hope it helps to easily identify the issue!
