### ISSUE TITLE
Dwarven Defender losing Defensive Stance bonuses after using items

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#484]
**To Reproduce**

 - Load attached save.
 - Turn on Defensive Stance (can be found in the quickbar)
 - Use an item such as any of the potions in the quickbar
 - The PC will lose the Defensive Stance
 - Reload the save
 - Turn on Defensive Stance
 - Start attacking the immortal goblin
 - Use an item while attacking
 - The PC will lose the Defensive Stance bonuses, but keep the Defensive Stance itself (the quickbar slot will still let you "cancel" DS)

**Specifics**

 - OS : Linux
 - Game build: 8193.34.1
 - Distro platform: GOG
 - Content overrides: None
 - Regression: No

**If needed, describe the bug**

I am not sure whether the intended behavior is for DS to be dropped whenever an item is used - if not, then that's the bug. But even if it's the intended behavior, DS not being cancelled (but bonuses still disappearing) is still a bug that can confuse the player who may look at their quickbar and believe he's still in DS.

[000021 - DDTest.zip](https://github.com/Beamdog/nwn-issues/files/10891684/000021.-.DDTest.zip)

**Comment by Prince-Raymond** [comment]
I agree that, at the very least, the bonuses disappearing while Defensive Stance is still displayed as active should be considered buggy behavior.

**Comment by Finaldeath** [comment]
Confirmed the bug, weird how using an item cancels it "properly" in one instance but not in another. I'll need to trace where the actions are cancelling it in the first place to fix and potentially add options so item usage doesn't cancel this specific stance.

I can't repo (from the wiki) any cases where it stays _immobile_ and loses all the bonuses however.

**Comment by Finaldeath** [comment]
@Taro94 need some thoughts on this one, I can probably look at fixing the bug clientside where it's not getting the cancelled part, but it looks like Bioware coded this in mostly intentionally primarily I think as a janky way to stop certain modes when casting item spells. It includes Stealth for instance. Doesn't cancel things like Expertise for instance.

A small gameplay tweak would be to treat Defensive Stance similar to things like Expertise and only cancel them in more limited circumstances. However it is a major buff to defensive stance and quite possibly done to somewhat balance it since in D&D had a somewhat limited duration instead - see: https://www.dandwiki.com/wiki/3e_SRD:Dwarven_Defender

**Comment by Finaldeath** [comment]
Also oddly I can't see an outline on defensive stance but can on expertise...weird?

**Comment by Taro94** [comment]
@Finaldeath I don't mind the bonuses disappearing and I agree it may have been done purposefully to keep DS balanced. I'd consider the bug fixed if the game properly cancelled the combat mode in these situations.

**Comment by Finaldeath** [comment]
Ok I've figured it out but yes making further gameplay altering changes probably isn't necessary/warranted (you could always script in re-enabling it in the spell script for free with IncrementRemainingFeatUses).
