### ISSUE TITLE
AdjustAlignment() feedback text for type ALIGNMENT_ALL is reversed

### ISSUE THREAD

**Issue by aaronmfparr** [Beamdog/nwn-issues#55]
**Problem**
Feedback text for AdjustAlignment() while using type ALIGNMENT_ALL is sometimes reversed
![alignment_all_ingame](https://user-images.githubusercontent.com/4274181/82157900-220c2300-9839-11ea-968e-a4249a95822d.png)
The alignment shift in the above example was applied correctly. Character is now Chaotic Evil, but the feedback text is off, mentioning a shift toward Good.

**To Reproduce**
 - Apply an alignment shift to the character with type ALIGNMENT_ALL
- Observe the feedback text.
![alignment_all](https://user-images.githubusercontent.com/4274181/82157869-d5c0e300-9838-11ea-9759-7046ea190ffc.png)

**Specifics**
 - OS (Windows)
 - 8193.13
 - Steam

**Comment by niv** [comment]
* Game will now not render any feedback if no alignment shift occurred (previously, it would render "Your alignment has shifted by -100" if you requested -100, even if you were already at rock bottom).
* Game will now render the actual alignment shift that has happened, instead of the requested one: AdjustAlignment(-100) when at 50 will now say "You have shifted by -35" (to get you to 15, where the good/evil notchiness is) instead of "You have shifted by -100" but still putting you to 15.
