### ISSUE TITLE
[8193.13 STABLE] Game Crashes Frequently when Using F9 from the Toolset

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#58]
**To Reproduce**

 - Open a module
 - Press F9
 - Game crashes (not every time, but very frequently).

OR

 - Open a module
 - Press F9
 - If Toolset doesn't crash, exit to main NWN Menu
 - Start the module from the NWN Main Menu
 - Game crashes.

**Specifics**

 - Game Build 8193.13 Stable

**If needed, describe the bug**

  - Crash logs attached
  - This crash occurs about 50% of the time BUT only if using F9 from the toolset

[CrashLogs.zip](https://github.com/Beamdog/nwn-issues/files/4650486/CrashLogs.zip)

**Comment by DMSymphony** [comment]
These crashes are not specific to the Toolset exactly.

I saw this crash from another player, and am waiting on them to give me more details, but they seem to have disappeared.

The part of the game that is crashing is reading the class of the character that is likely automatically selected when starting this module. It's possible you will experience this crash playing another module from nwmain.exe instead of the toolset if you play with this character. It seems like the part that is crashing specifically is checking to see what specialty of a wizard the character is.

If you can find out what character the F9 is automatically choosing, which is usually the character in your character vault with the first alphabetical name, and tell me which character it is, possibly sending me the .bic, and seeing if it crashes in other module loads not from the toolset, I can narrow down the scope of this issue considerably.

**Comment by pstemarie** [comment]
Symphony,

I think the crash is actually related to the PRC v3.9.1 which was in one of the modules I was trying out. I had made a wizard in that module, then forgotten to remove it from my local vault after I finished testing. Thus, when testing out my other module (which doesn't use the PRC), the crash would occur.

I have removed the character from the vault and am now loading with the Aluvian Darkstar character from the vanilla assets. 

The crash is apparently now gone. Attached is a copy of the PRC character's bic if you still want to take a look.

[_fatty_test.zip](https://github.com/Beamdog/nwn-issues/files/4655528/_fatty_test.zip)

**Comment by DMSymphony** [comment]
Well, that's good to hear.

I've seen some issues with PRC crashes in recent tickets, but I can't dive into PRC right now to learn how it all works and try to diagnose them.

I've been having some issues with the new rules system because of the vault validating local characters when DMing a module with no haks with characters from servers with racial customization, I am worried that this may need to lead to some vault ettiquette during these experimental times. It's one thing to check to make sure your override folders are empty etc. when having problems, but your issue happens just as easily with no haks or overrides.

I'm closing this issue for now. Thanks for reporting.
