### ISSUE TITLE
[8193.14 preview] - Shield texture rendering - preview

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#83]
**To Reproduce**

 - Edit or create either a Small, Large or Tower Shield in the toolset.
 - Click on various shields, look at the model in the preview box.
 - Some specific models are missing textures in the toolset

Textures on some shields previewed in the toolset appear as black. This does not affect all shields, and they look normal when in-game. 

![image](https://user-images.githubusercontent.com/51026560/83980367-2204bd80-a8e3-11ea-9d9f-9c742948349e.png)

In this screenshot, shields 011, 012, 013 appear as black, but 021, 022, 023 preview correctly. This affects some Large and Tower Shields as well.

**Specifics**
 - Game build: 8193.14
- OS: Windows 10
- Graphic Card: NVIDIA GeForce GTX 960M (integrated)

**Comment by Soren217** [comment]
This is actually caused by models haven ambient light property set to 0. I figure it helps expose model errors, but not in the most constructive way so going to restore the default behavior.

**Comment by DMSymphony** [comment]
These models are silly, and have random ambient and diffuse multipliers. This is clearly not intentional, and causes the models to go black in areas with low ambient light (diffuse only areas) as well. 

I was going to try to push some 100% lit versions of the models a few years ago as part of a fixed package, but the release of the Beamdog shields came out the same week and I didn’t want to deal with the resource collisions.

Whether the toolset behavior is changed or not, it may be prudent to make some candidates for a big patch.

**Comment by FrogsOfDoom** [comment]
This seems to be fixed.
