### ISSUE TITLE
[8193.14 preview] - Misc minor palette creature/item issues

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#95]
**Description**

The Half-Dragon - Red and Malaugrym have no descriptions. Seems odd since the other new additions have descriptions. Disregard if intentional.

The Half-Dragon - Red is classified as a NPC - Other in the palette rather than a Monster - Dragon. It's also a Chaotic Good level 1 elf fighter. Seems off:
![image](https://user-images.githubusercontent.com/51026560/84218157-db0df800-aa9b-11ea-8be4-2aae12fcff9e.png)

The Brass Candleholder's description is the same one as the standard torch. Also, very minor but its Light is Orange, it may be best for it to be Yellow or White since it's a candle rather than a torch. Also, its "hitbox"/glow in-game is pretty big:
![image](https://user-images.githubusercontent.com/51026560/84218491-84ed8480-aa9c-11ea-80e0-4057f8d2e046.png)

**To Reproduce**

 -  Look at creatures/items in the toolset or in-game.

**Comment by Bill-Harper** [comment]
![candelholder_repair](https://user-images.githubusercontent.com/53191846/86146791-a7d0ee80-bac6-11ea-9854-b0d14649f8ee.png)

I managed to repair the bounding box, a little trick with shrinking the aurora base down in scale before assembling the model as well as moving some stray pivots (no collision per se, usually what defines bound box). I also welded the meshes back together into proper pieces while retaining proper shadows.  At same time I moved the smoke emitter up a dozen cm or so--so it didn't smoke from the middle of the candlestick instead of the wick. And finally, I swapped the Orange light 5m for Yellow 5m.

I'll take a look at blueprints next session; there are a few others in need of assistance especially in the creature section. Goal is to aim for 3E canon rules.
