### ISSUE TITLE
[Since Pre EE] Placeable and Tile Lighting (Main & Source) is Broken, RecomputeStaticLighting is Broken

### ISSUE THREAD

**Issue by ghost** [Beamdog/nwn-issues#99]
**To Reproduce**

- Create an area in the toolset 
- Set the sourcelights to black.
- Write an OnEnter script to turn the sourcelights on (set a color).
- Write an OnHeartbeat script to change the sourcelight color to a different color.
- The OnHeartbeat color change does not occur and RecomputeStaticLighting fails.

- Create an area in the toolset 
- Set the main lights to black.
- Write an OnHeartbeat script to change the main lights' color.
- The lights do not change color when RecomputeStaticLighting is called.

- Create an area in the toolset 
- Place some usable placeable lights.
- Set the lights to "Deactivated".
- Write an OnEnter script to activate the lights.
- Write an OnHeartbeat event to deactivate the lights.
- Only some of the lights come on and when RecomputeStaticLighting is called lighting in the area doesn't not update properly.
- When the OnHeartbeat fires, the lights go off, but the glow remains as does any lighting from them when RecomputeStaticLighting is called.

**Specifics**

 - Windows 10
 - This issue predates EE and iirc, originated in v1.67
 - Steam (affects all PC platforms)
 - None

**Describe the Issue**

See above, I think its descriptive enough and Symphony and I discussed this at some length last Fall while I was working on my module.

**Comment by Finaldeath** [comment]
Further to this me and Lokey had a gander and on the latest preview the new lightning engine appears to work fine (albeit source lights tend to overwhelm main lights0, while disabling the new lighting it turned into a mess of "Source lights half work", "main lights sometimes can recompute if set to black first" and us also not understanding how you can turn off source lights at all (if it ever could be done!). I'd suggest the thing is fixed if only because some modules are made with old lighting, and it also affects placeable illuminations.

So anyway RecomputeStaticLighting() certainly is broken to some degree. Lokey had a quick test module where you can text-chat to do different commands, useful to test that. He might attach it here or I guess I could if someone wanted it.

**Comment by Lokey7** [comment]
I'll add a streamlined command to my test module and attach.

**Comment by Finaldeath** [comment]
So there are some really weird things going on even with the new lighting engine. At the very least source lights going to black (255) doesn't work right away on source lights, needs an area transition (and is undocumented anyway only found through testing). The legacy lighting engine is very broken for all kinds of situations (off, on, area transition or not sometimes). An area transition is a weird way to "fix" anything of course, and unusable for any discos :(

**Comment by Lokey7** [comment]
I also tried FadeTo/FromBlack, no change in behavior.
